import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';

// ─── Git utilities ──────────────────────────────────────────────────

export function isGitRepo(dir: string): boolean {
  try {
    execSync('git rev-parse --is-inside-work-tree', { cwd: dir, stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

export function getGitBranch(dir: string): string {
  try {
    return execSync('git branch --show-current', { cwd: dir, stdio: 'pipe' })
      .toString()
      .trim();
  } catch {
    return 'unknown';
  }
}

export function getGitDiff(dir: string): string {
  try {
    const staged = execSync('git diff --cached --stat', { cwd: dir, stdio: 'pipe' }).toString();
    const unstaged = execSync('git diff --stat', { cwd: dir, stdio: 'pipe' }).toString();
    return [staged, unstaged].filter(Boolean).join('\n');
  } catch {
    return '';
  }
}

export function getGitDiffFull(dir: string): string {
  try {
    const diff = execSync('git diff HEAD', { cwd: dir, stdio: 'pipe', maxBuffer: 1024 * 1024 * 5 }).toString();
    // Truncate if too large
    if (diff.length > 50000) {
      return diff.substring(0, 50000) + '\n... (truncated, diff too large)';
    }
    return diff;
  } catch {
    return '';
  }
}

export function getChangedFiles(dir: string): string[] {
  try {
    const output = execSync('git status --porcelain', { cwd: dir, stdio: 'pipe' }).toString();
    return output
      .split('\n')
      .filter(Boolean)
      .map(line => line.trim());
  } catch {
    return [];
  }
}

export function getGitLog(dir: string, count: number = 5): string {
  try {
    return execSync(`git log --oneline -${count}`, { cwd: dir, stdio: 'pipe' }).toString().trim();
  } catch {
    return '';
  }
}

// ─── CLAUDE.md helpers ──────────────────────────────────────────────

const HANDOFF_MARKER_START = '<!-- claude-synk:handoff-start -->';
const HANDOFF_MARKER_END = '<!-- claude-synk:handoff-end -->';

export function injectHandoff(projectDir: string, handoffContent: string): void {
  const claudeMdPath = path.join(projectDir, 'CLAUDE.md');
  let existing = '';

  if (fs.existsSync(claudeMdPath)) {
    existing = fs.readFileSync(claudeMdPath, 'utf-8');
    // Remove old handoff if present
    const startIdx = existing.indexOf(HANDOFF_MARKER_START);
    const endIdx = existing.indexOf(HANDOFF_MARKER_END);
    if (startIdx !== -1 && endIdx !== -1) {
      existing = existing.substring(0, startIdx) + existing.substring(endIdx + HANDOFF_MARKER_END.length);
      existing = existing.trim();
    }
  }

  const handoffBlock = `
${HANDOFF_MARKER_START}
## Previous Session Handoff (by Claude Synk)

${handoffContent}

> This handoff was automatically generated by [claude-synk](https://github.com/anthropics/claude-synk).
> After reading this, continue the work described above.

${HANDOFF_MARKER_END}
`;

  const newContent = handoffBlock.trim() + '\n\n' + existing;
  fs.writeFileSync(claudeMdPath, newContent.trim() + '\n');
}

export function removeHandoff(projectDir: string): void {
  const claudeMdPath = path.join(projectDir, 'CLAUDE.md');
  if (!fs.existsSync(claudeMdPath)) return;

  let content = fs.readFileSync(claudeMdPath, 'utf-8');
  const startIdx = content.indexOf(HANDOFF_MARKER_START);
  const endIdx = content.indexOf(HANDOFF_MARKER_END);

  if (startIdx !== -1 && endIdx !== -1) {
    content = content.substring(0, startIdx) + content.substring(endIdx + HANDOFF_MARKER_END.length);
    content = content.trim();
    if (content.length === 0) {
      fs.unlinkSync(claudeMdPath);
    } else {
      fs.writeFileSync(claudeMdPath, content + '\n');
    }
  }
}

// ─── Claude auth helpers ────────────────────────────────────────────

export function getClaudeCredentialFiles(): string[] {
  const claudeDir = path.join(require('os').homedir(), '.claude');
  if (!fs.existsSync(claudeDir)) return [];

  return fs.readdirSync(claudeDir).filter(f => {
    const lower = f.toLowerCase();
    return lower.includes('credentials') ||
           lower.includes('auth') ||
           lower.includes('token') ||
           lower.includes('.json');
  });
}

export function backupClaudeAuth(backupDir: string, accountName: string): void {
  const claudeDir = path.join(require('os').homedir(), '.claude');
  const targetDir = path.join(backupDir, accountName);

  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true, mode: 0o700 });
  }

  const files = getClaudeCredentialFiles();
  for (const file of files) {
    const src = path.join(claudeDir, file);
    const dest = path.join(targetDir, file);
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
      fs.chmodSync(dest, 0o600);
    }
  }
}

export function restoreClaudeAuth(backupDir: string, accountName: string): boolean {
  const claudeDir = path.join(require('os').homedir(), '.claude');
  const sourceDir = path.join(backupDir, accountName);

  if (!fs.existsSync(sourceDir)) return false;

  const files = fs.readdirSync(sourceDir);
  for (const file of files) {
    const src = path.join(sourceDir, file);
    const dest = path.join(claudeDir, file);
    fs.copyFileSync(src, dest);
    fs.chmodSync(dest, 0o600);
  }

  return true;
}

// ─── Display helpers ────────────────────────────────────────────────

export function printBox(title: string, content: string): void {
  const lines = content.split('\n');
  const maxLen = Math.max(title.length, ...lines.map(l => l.length));
  const border = '─'.repeat(maxLen + 2);

  console.log(chalk.cyan(`┌${border}┐`));
  console.log(chalk.cyan('│') + chalk.bold.white(` ${title.padEnd(maxLen)} `) + chalk.cyan('│'));
  console.log(chalk.cyan(`├${border}┤`));
  for (const line of lines) {
    console.log(chalk.cyan('│') + ` ${line.padEnd(maxLen)} ` + chalk.cyan('│'));
  }
  console.log(chalk.cyan(`└${border}┘`));
}

export function formatTimestamp(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleString();
}

export function generateId(): string {
  const now = new Date();
  const ts = now.toISOString().replace(/[^0-9]/g, '').substring(0, 14);
  const rand = Math.random().toString(36).substring(2, 6);
  return `${ts}_${rand}`;
}
